name: 'Search of posts config'
description: 'Search of posts, captcha for comments in post,'
type: module
core: 8.x
dependencies:
  - block
  - captcha
  - comment
  - facets
  - field
  - my_
  - node
  - search_api
  - search_api_db
  - search_api_solr
  - system
  - taxonomy
  - taxonomy_menu
  - text
  - user
  - views
version: 8.x
